import logging
import time
from datetime import datetime

# Configure logger
logger = logging.getLogger('EDUGuard.AlertManager')

class AlertManager:
    """Manages posture alerts generated by the monitoring system"""
    
    ALERT_LEVELS = {
        'info': 0,
        'warning': 1, 
        'critical': 2
    }
    
    def __init__(self, db_manager):
        """Initialize the alert manager
        
        Args:
            db_manager: Database manager instance for storing alerts
        """
        self.db_manager = db_manager
        self.alert_thresholds = {
            'posture': {
                'bad_percentage_threshold': 60,  # Alert if >60% bad posture
                'minimum_samples': 10,           # Need at least 10 samples
                'cooldown_seconds': 300          # 5 minutes between alerts
            }
        }
        self.last_alert_times = {}
        
    def check_posture_alert(self):
        """Check if bad posture exceeds threshold and generate alerts"""
        try:
            # Get posture average for the last 5 minutes
            posture_avg = self.db_manager.calculate_prediction_average('posture', minutes=5)
            
            if not posture_avg:
                logger.debug("No posture data available for alert check")
                return
                
            bad_posture_percentage = posture_avg.get('bad_posture_percentage', 0)
            total_samples = posture_avg.get('total_samples', 0)
            
            logger.debug(f"Posture check: {bad_posture_percentage:.1f}% bad posture ({total_samples} samples)")
            
            # Only trigger if we have enough samples
            if total_samples < self.alert_thresholds['posture']['minimum_samples']:
                logger.debug(f"Not enough samples for alert ({total_samples} < {self.alert_thresholds['posture']['minimum_samples']})")
                return
                
            # Check if bad posture exceeds threshold
            threshold = self.alert_thresholds['posture']['bad_percentage_threshold']
            if bad_posture_percentage > threshold:
                cooldown = self.alert_thresholds['posture']['cooldown_seconds']
                if self._can_trigger_alert('bad_posture', cooldown):
                    self.db_manager.save_alert(
                        'posture',
                        f'Poor posture detected! {bad_posture_percentage:.1f}% bad posture in the last 5 minutes',
                        'warning',
                        {
                            'bad_posture_percentage': bad_posture_percentage,
                            'total_samples': total_samples,
                            'good_posture_count': posture_avg.get('good_posture_count', 0),
                            'bad_posture_count': posture_avg.get('bad_posture_count', 0),
                            'threshold': threshold
                        }
                    )
                    self._update_alert_time('bad_posture')
                    logger.warning(f"🚨 Bad posture alert triggered: {bad_posture_percentage:.1f}% (threshold: {threshold}%)")
                else:
                    logger.debug(f"Bad posture detected but still in cooldown period")
            else:
                logger.debug(f"Posture within acceptable range: {bad_posture_percentage:.1f}% < {threshold}%")
                
        except Exception as e:
            logger.error(f"Error checking posture alert: {e}")
    
    def trigger_immediate_posture_alert(self, bad_posture_percentage, context_data=None):
        """Directly trigger a posture alert bypassing normal checks
        
        Args:
            bad_posture_percentage (float): The percentage of bad posture
            context_data (dict): Additional context data for the alert
        """
        try:
            alert_data = {
                'bad_posture_percentage': bad_posture_percentage,
                'trigger_type': 'immediate',
                'timestamp': int(time.time() * 1000)
            }
            
            if context_data:
                alert_data.update(context_data)
            
            self.db_manager.save_alert(
                'posture',
                f'Poor posture detected! {bad_posture_percentage:.1f}% bad posture',
                'warning',
                alert_data
            )
            
            logger.warning(f"🚨 Immediate posture alert triggered: {bad_posture_percentage:.1f}%")
            
        except Exception as e:
            logger.error(f"Error triggering immediate posture alert: {e}")
    
    def _can_trigger_alert(self, alert_type, cooldown_seconds=300):
        """Check if enough time has passed to trigger an alert
        
        Args:
            alert_type (str): Type of alert
            cooldown_seconds (int): Minimum seconds between alerts of this type
            
        Returns:
            bool: True if alert can be triggered, False if still in cooldown
        """
        if alert_type not in self.last_alert_times:
            return True
            
        last_time = self.last_alert_times[alert_type]
        time_elapsed = time.time() - last_time
        
        logger.debug(f"Alert cooldown check for {alert_type}: {time_elapsed:.1f}s elapsed (need {cooldown_seconds}s)")
        
        return time_elapsed >= cooldown_seconds
    
    def _update_alert_time(self, alert_type):
        """Update the last time an alert was triggered
        
        Args:
            alert_type (str): Type of alert
        """
        self.last_alert_times[alert_type] = time.time()
        logger.debug(f"Updated last alert time for {alert_type}")
    
    def get_alert_status(self):
        """Get current alert status and statistics
        
        Returns:
            dict: Alert status information
        """
        try:
            # Get recent alerts
            recent_alerts = self.db_manager.get_recent_alerts(limit=10)
            posture_alerts = [alert for alert in recent_alerts if alert.get('type') == 'posture']
            
            # Get posture statistics
            posture_avg = self.db_manager.calculate_prediction_average('posture', minutes=5)
            
            return {
                'total_alerts': len(recent_alerts),
                'posture_alerts': len(posture_alerts),
                'recent_alerts': posture_alerts[:5],  # Last 5 posture alerts
                'current_posture_stats': posture_avg,
                'last_alert_times': self.last_alert_times.copy()
            }
            
        except Exception as e:
            logger.error(f"Error getting alert status: {e}")
            return {
                'error': str(e),
                'total_alerts': 0,
                'posture_alerts': 0,
                'recent_alerts': [],
                'current_posture_stats': None,
                'last_alert_times': {}
            } 